/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  output: 'standalone',
  
  // Custom webpack configuration to exclude disabled pages
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    // List of disabled pages - all pages except the 3 active ones
    const disabledPages = [
      '401k-calculator',
      'about',
      'age-calculator',
      'amortization-calculator',
      'annuity-calculator',
      'annuity-payout-calculator',
      'apr-calculator',
      'area-calculator',
      'army-body-fat-calculator',
      'auto-lease-calculator',
      'auto-loan-calculator',
      'average-return-calculator',
      'bac-calculator',
      'bandwidth-calculator',
      'big-number-calculator',
      'binary-calculator',
      'bmi-calculator',
      'bmr-calculator',
      'body-fat-calculator',
      'body-surface-area-calculator',
      'body-type-calculator',
      'bond-calculator',
      'bra-size-calculator',
      'btu-calculator',
      'budget-calculator',
      'business-loan-calculator',
      'calculators',
      'calorie-calculator',
      'calories-burned-calculator',
      'carbohydrate-calculator',
      'cash-back-or-low-interest-calculator',
      'cd-calculator',
      'circle-calculator',
      'college-cost-calculator',
      'commission-calculator',
      'compound-interest-calculator',
      'conception-calculator',
      'concrete-calculator',
      'confidence-interval-calculator',
      'contact',
      'conversion-calculator',
      'credit-card-calculator',
      'credit-cards-payoff-calculator',
      'currency-calculator',
      'date-calculator',
      'day-counter',
      'day-of-week',
      'day-of-week-calculator',
      'debt-consolidation-calculator',
      'debt-payoff-calculator',
      'debt-to-income-ratio-calculator',
      'density-calculator',
      'depreciation-calculator',
      'dew-point-calculator',
      'dice-roller',
      'discount-calculator',
      'distance-calculator',
      'dividend-calculator',
      'down-payment-calculator',
      'due-date-calculator',
      'electricity-calculator',
      'engine-horsepower-calculator',
      'estate-tax-calculator',
      'exponent-calculator',
      'factor-calculator',
      'fat-intake-calculator',
      'fha-loan-calculator',
      'finance-calculator',
      'fraction-calculator',
      'fuel-cost-calculator',
      'future-value-calculator',
      'gas-mileage-calculator',
      'gcf-calculator',
      'gdp-calculator',
      'gfr-calculator',
      'golf-handicap-calculator',
      'gpa-calculator',
      'grade-calculator',
      'gravel-calculator',
      'half-life-calculator',
      'healthy-weight-calculator',
      'heat-index-calculator',
      'height-calculator',
      'hex-calculator',
      'horsepower-calculator',
      'hours-calculator',
      'house-affordability-calculator',
      'how-many-days',
      'ideal-weight-calculator',
      'income-tax-calculator',
      'inflation-calculator',
      'interest-calculator',
      'interest-rate-calculator',
      'investment-calculator',
      'ip-subnet-calculator',
      'ira-calculator',
      'jsonl-converter',
      'jsonl-validator',
      'lcm-calculator',
      'lean-body-mass-calculator',
      'lease-calculator',
      'life-expectancy-calculator',
      'loan-calculator',
      'loan-comparison-calculator',
      'loan-payoff-calculator',
      'log-calculator',
      'love-calculator',
      'macro-calculator',
      'margin-calculator',
      'marriage-calculator',
      'marriage-tax-calculator',
      'mass-calculator',
      'matrix-calculator',
      'mean-calculator',
      'mean-median-mode-range-calculator',
      'median-calculator',
      'mileage-calculator',
      'military-retirement-calculator',
      'mode-calculator',
      'molarity-calculator',
      'molecular-weight-calculator',
      'mortgage-calculator',
      'mortgage-payoff-calculator',
      'mortgage-refinance-calculator',
      'mulch-calculator',
      'net-worth-calculator',
      'number-sequence-calculator',
      'odds-calculator',
      'ohms-law-calculator',
      'one-rep-max-calculator',
      'overtime-calculator',
      'ovulation-calculator',
      'pace-calculator',
      'password-generator',
      'payback-period-calculator',
      'payment-calculator',
      'pension-calculator',
      'percent-error-calculator',
      'percentage-calculator',
      'period-calculator',
      'permutation-calculator',
      'permutation-combination-calculator',
      'personal-loan-calculator',
      'population-calculator',
      'pregnancy-calculator',
      'pregnancy-conception-calculator',
      'pregnancy-weight-gain-calculator',
      'present-value-calculator',
      'price-calculator',
      'privacy-policy',
      'probability-calculator',
      'protein-calculator',
      'pythagorean-theorem-calculator',
      'quadratic-equation-calculator',
      'quadratic-formula-calculator',
      'random-number-generator',
      'ratio-calculator',
      'real-estate-calculator',
      'refinance-calculator',
      'rent-calculator',
      'rent-vs-buy-calculator',
      'rental-property-calculator',
      'repayment-calculator',
      'resistor-calculator',
      'retirement-calculator',
      'right-triangle-calculator',
      'rmd-calculator',
      'roi-calculator',
      'roofing-calculator',
      'root-calculator',
      'roth-ira-calculator',
      'rounding-calculator',
      'salary-calculator',
      'sales-tax-calculator',
      'sample-size-calculator',
      'savings-calculator',
      'scientific-calculator',
      'scientific-notation-calculator',
      'simple-interest-calculator',
      'sleep-calculator',
      'slope-calculator',
      'social-security-calculator',
      'speed-calculator',
      'square-footage-calculator',
      'stair-calculator',
      'standard-deviation-calculator',
      'statistics-calculator',
      'stock-calculator',
      'student-loan-calculator',
      'surface-area-calculator',
      'take-home-pay-calculator',
      'take-home-paycheck-calculator',
      'tax-bracket-calculator',
      'tdee-calculator',
      'terms',
      'tile-calculator',
      'time-calculator',
      'time-duration-calculator',
      'time-zone-calculator',
      'tip-calculator',
      'tire-size-calculator',
      'triangle-calculator',
      'unit-conversion-calculator',
      'unit-converter',
      'va-loan-calculator',
      'va-mortgage-calculator',
      'vat-calculator',
      'voltage-drop-calculator',
      'volume-calculator',
      'water-intake-calculator',
      'weight-calculator',
      'weight-loss-calculator',
      'wind-chill-calculator',
      'yearly-salary-calculator',
      'z-score-calculator'
    ]
    
    // Only apply in production build
    if (!dev) {
      // Add environment variable for disabled pages
      config.plugins.push(
        new webpack.DefinePlugin({
          'process.env.DISABLED_PAGES': JSON.stringify(disabledPages),
        })
      )
      
      // Exclude disabled pages from build by modifying the resolve
      config.resolve.alias = {
        ...config.resolve.alias,
        // Redirect disabled pages to a dummy component
        ...Object.fromEntries(
          disabledPages.map(page => [
            `@/app/${page}/page`,
            require.resolve('./src/components/DisabledPage.tsx')
          ])
        )
      }
    }
    
    return config
  },
  
  // Disable specific pages during build
  async rewrites() {
    return [
      // Redirect disabled pages to 404
      {
        source: '/:path*',
        destination: '/404',
        has: [
          {
            type: 'header',
            key: 'x-disable-page',
          },
        ],
      },
    ]
  },
}

module.exports = nextConfig
